global:
  scrape_interval: 1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['coba-prometheus:9090']
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "cobaApp"
    metrics_path: /metrics

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['coba-app:5005']